---
region: 'eu-west-2'
availability_zones:
  - "eu-west-2a"
  - "eu-west-2b"

component: 'test'
deployment_identifier: "%{hiera('seed')}"

vpc_cidr: "10.1.0.0/16"

domain_name: 'infrablocks.click'

public_zone_id: "Z08829023L5IPIQBJOX63"
private_zone_id: 'Z0211739BXR21FNN139O'

allow_cidrs:
  - "0.0.0.0/0"

service_name: 'service-1'
service_port: 80

access_logs_bucket: "ecs-load-balancer-%{hiera('deployment_identifier')}"
access_logs_bucket_prefix: "test-%{hiera('deployment_identifier')}"
access_logs_interval: 5
