---
configuration_directory: "%{cwd}/examples/full"
state_file: "%{cwd}/state/full.tfstate"
vars:
  region: "%{hiera('region')}"
  availability_zones: "%{hiera('availability_zones')}"
  vpc_cidr: "%{hiera('vpc_cidr')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  domain_name: "%{hiera('domain_name')}"
  public_zone_id: "%{hiera('public_zone_id')}"
  private_zone_id: "%{hiera('private_zone_id')}"

  access_logs_bucket: "%{hiera('access_logs_bucket')}"
  access_logs_bucket_prefix: "%{hiera('access_logs_bucket_prefix')}"
